services:
    postgres:
        image: postgres:17
        container_name: second_brain_postgres
        restart: always

        ports:
            - "5432:5432"

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: second_brain

        volumes:
            - second_brain_data:/var/lib/postgresql/data

volumes:
    second_brain_data:
